# Generated by Django 4.1 on 2023-04-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_options_alter_dish_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('Супы', 'Супы'), ('Гарниры', 'Гарниры'), ('Основные блюда', 'Основные блюда'), ('Салаты', 'Салаты'), ('Десерты', 'Десерты'), ('Напитки', 'Напитки'), ('Другое', 'Другое')], max_length=55),
        ),
        migrations.AddField(
            model_name='dish',
            name='title',
            field=models.CharField(blank=True, choices=[('Завтрак', 'Завтрак'), ('Обед', 'Обед'), ('Ужин', 'Ужин'), ('Перекус', 'Перекус')], max_length=55),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dish',
            name='steps',
            field=models.CharField(blank=True, max_length=2255),
        ),
    ]
