# Generated by Django 4.1 on 2023-04-26 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_category_title_category_detail_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='detail',
            field=models.TextField(blank=True, max_length=2255),
        ),
    ]
