# Generated by Django 4.1 on 2023-04-30 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dish_category_alter_category_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='cook_time',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='calorie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='КБЖУ'),
        ),
        migrations.AddField(
            model_name='dish',
            name='url',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='detail',
            field=models.TextField(blank=True, max_length=2255, verbose_name='Описания'),
        ),
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.CharField(max_length=2255, verbose_name='Ингридиенты'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=55, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='steps',
            field=models.CharField(blank=True, max_length=5555, verbose_name='Рецепт'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=55, verbose_name='Имя')),
                ('detail', models.TextField(max_length=2255, verbose_name='Отзыв')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dish', verbose_name='блюдо')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.review')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='api.category', verbose_name='Категория'),
        ),
    ]
