# Generated by Django 4.1 on 2023-05-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_dish_category_alter_dish_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ManyToManyField(default='default_category', related_name='category', to='api.category', verbose_name='Категория'),
        ),
    ]
